/*
 * This source file was generated by the Gradle 'init' task
 */
package org.authservice;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

@SpringBootApplication
@EnableJpaRepositories(basePackages = {"authService.repository"})
@ComponentScan(basePackages = {"authService.controller", "authService.auth", "authService.service"})
public class App {

    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
